### ISSUE TITLE
Suggestion: Add rescan translations button 

### ISSUE THREAD

**Issue by uran1980** [zelenin/yii2-i18n-module#10]
I think it is good idea to have "rescan" button in translations module that scan project in predefined places for Yii::t or Module::t or whatever.

MissingTranslationEvent fire only on visited pages. What about translation messages that exists in place that hard to find, but this messages need to be translated anyway.

**Comment by golles** [comment]
I would also like a button that scans the project instead of using the command line tool

**Comment by Tak0r** [comment]
i would also love to have this feature!

**Comment by uran1980** [comment]
I'm create **[yii2-translate-panel](https://github.com/uran1980/yii2-translate-panel)** package based on this **yii-i18n-module** package with more usability in mind.
You can [check it out](https://github.com/uran1980/yii2-translate-panel).

**Comment by Tak0r** [comment]
OMG this is awesome!

**Comment by zelenin** [comment]
@uran1980 
```php
Getting unknown property: uran1980\yii\modules\i18n\models\SourceMessage::location
```
```uran1980\yii2-translate-panel\views\default\_source-message-content.php – yii\db\BaseActiveRecord::__get('location') at line 6```

**Comment by zelenin** [comment]
Rescan should be is a console command, because it's very expensive and long time task for web script..

**Comment by zelenin** [comment]
@uran1980 ```The use statement with non-compound name 'Yii' has no effect```
```uran1980\yii2-translate-panel\views\default\_message-tabs.php at line 3```

**Comment by uran1980** [comment]
Db structure changed: added location field.
I checked on new project with yii-app-advanced template.
For new project you need to run migration file:
```
php yii migrate --migrationPath=@uran1980/yii/modules/i18n/migrations
```
For old projects with existed db I'll try to fix this.

**Comment by uran1980** [comment]
@zelenin Rescan algoritm taked from yii2 console messageController ```yiisoft\yii2\console\controllers\MessageController.php``` with minor changes for web interface.

**Comment by zelenin** [comment]
@uran1980 no difference what algorythm. Filesystem scan should be console command.

**Comment by zelenin** [comment]
@uran1980 if you want it you may it ) I said what I think

**Comment by uran1980** [comment]
@zelenin ok I'm fix errors. Thanks!
