### ISSUE TITLE
Class Zelenin\yii\modules\I18n\Components\Language does not exist

### ISSUE THREAD

**Issue by dbsparkle** [zelenin/yii2-i18n-module#11]
I have installed the module via composer (as it was written in doc), 
but the application fails to find it... 

![_012115_040249_pm](https://cloud.githubusercontent.com/assets/417757/5832323/f2b74624-a186-11e4-94f7-3060153c1f28.jpg)

**Comment by zelenin** [comment]
this file not exists in this module. where is calling it in your app?

**Comment by dbsparkle** [comment]
in common/config/main.php

	'components' => [
			'i18n' => [
				'class'=> Zelenin\yii\modules\I18n\components\I18N::className(),
	    		//'languages' => ['ru', 'de', 'it','ja'],
			    'translations' => [
	        		'yii' => [
			            'class' => yii\i18n\DbMessageSource::className()
	        		]
				]
			],
	    ],

**Comment by zelenin** [comment]
you do something wrong.
Language class not exists in this module.
And namespace Components too.
See full error trace for place where this class is initialized.

**Comment by dbsparkle** [comment]
Shame on me! You`re totally right!
