### ISSUE TITLE
yii\db\Exception translating message

### ISSUE THREAD

**Issue by alinv04** [zelenin/yii2-i18n-module#12]
On a Postgresql database Zelenin\yii\modules\I18n\Module::missingTranslation throws
Exception (Database Exception) 'yii\db\Exception' with message 'SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "$2"
LINE 1: ...e_message_table" WHERE category = $1 and message = binary $2
^
The SQL being executed was: SELECT * FROM "source_message_table" WHERE category = 'app' and message = binary 'ID'' 

The 'binary' keyword causes postgresql to throw the error

**Comment by zelenin** [comment]
try 0.1.6 version
