### ISSUE TITLE
Where to go for translating messages on localhost?

### ISSUE THREAD

**Issue by cloudswitch** [zelenin/yii2-i18n-module#14]
Hi, and where to go for translating messages on localhost? Thx!

**Comment by zelenin** [comment]
```Go to http://backend.yourdomain.com/translations for translating your messages```

**Comment by cloudswitch** [comment]
Hi Aleksandr,

but I don't have a .com domain jet, and unfortunately this way this module doesn't work for me. I know I'm a lame but I can't find where to access it on localhost. Can you please help me a little bit? Thanks a lot!

**Comment by zelenin** [comment]
```backend.yourdomain.com``` is your domain for backend. backend.localhost or 127.0.0.1/backend or mydev.dev/admin...

**Comment by cloudswitch** [comment]
Interesting, but for me only a blank page 
http://backend.yourdomain.com/translations - ERR_NAME_NOT_RESOLVED
http://backend.localhost/translations - Wamp server configuration page
http://localhost/yiicomm/backend/web/index.php?r=translations - Page not found.
http://localhost/yiicomm/backend/translations - Wamp server configuration page
etc.

I guess I have tried at least 10 different ways to reach it with no luck, and of course it's only a stupid small thing what I don't know jet, maybe my settings are different (I have a basic routing jet, so this is how it works by me: http://localhost/yiicomm/backend/web/index.php?r=controller).

Thank you!

**Comment by zelenin** [comment]
http://localhost/yiicomm/backend/web/index.php?r=i18n/default/index

**Comment by cloudswitch** [comment]
Man, I would've never been able to find this out... :D
Thank you very much! Finally it works!!!
