### ISSUE TITLE
Is there a way to run on yii2 basic template?

### ISSUE THREAD

**Issue by cloudswitch** [zelenin/yii2-i18n-module#15]
Hi,

I have a yii2 basic template, and I've done this:
```
'components' => [
        'i18n' => [
            'class' => Zelenin\yii\modules\I18n\components\I18N::className(),
            'languages' => ['en-EN']
        ],
```
and this:
```
'modules' => [
        'i18n' => Zelenin\yii\modules\I18n\Module::className(),
    ],
```
in **config/web** but unfortunately it doesn't seem to work to migrate (Exception: you should configure component). Maybe because it was planned only for advanced template? Is there a way to run on yii2 basic template, too? Thanks!

**Comment by zelenin** [comment]
``` you should configure component```
advanced or basic - no difference

**Comment by cloudswitch** [comment]
okay, so it means, I have configured it correctly? so it must be configured in **config/web.php**, as I don't have separate common and backend config? but then why doesn't it work? Or have I configured something wrong...? Thanks!

**Comment by zelenin** [comment]
you don't configure component for console imo.

**Comment by cloudswitch** [comment]
Perfect! Good to know! Thanks for the info, it works now!
