### ISSUE TITLE
it does not work properly

### ISSUE THREAD

**Issue by gomonkey** [zelenin/yii2-i18n-module#19]
Some translation working, some other else not.
for example, in the menuI have at the moment no problem
`<?php echo \Yii::t('app', 'Contatti');?>`
for italian show the test word Contatti! and for English show the word Contacts
in other translation in the page not working, for example
`<?php echo \Yii::t('app', 'Carica foto');?>` have to show me "Upload Photo" for english translation.

I change lang by post and cookies and if I need, I setting this `\Yii::$app->language`

how is it possible? is an issue ?

![Image](https://i.imgur.com/Zw5Rdvr.jpg)

the query is correct:

`(SELECT `t1`.`message` AS `message`, `t2`.`translation` AS `translation` FROM `source_message` `t1`, `message` `t2` WHERE t1.id = t2.id AND t1.category = 'app' AND t2.language = 'en-EN') UNION ALL ( SELECT `t1`.`message` AS `message`, `t2`.`translation` AS `translation` FROM `source_message` `t1`, `message` `t2` WHERE (t1.id = t2.id AND t1.category = 'app' AND t2.language = 'en') AND (t2.id NOT IN (SELECT id FROM `message` WHERE language = 'en-EN')) )`

and the result are correct too, example:
Message | Translation
Carica foto | Upload photo

**Comment by zelenin** [comment]
it's not this extension issue.
translation works via native yii translation. It's only bakend for messages translating in Admin Panel.

**Comment by gomonkey** [comment]
yes ok, but not take all messages to translate.
