### ISSUE TITLE
How to translate messages in controllers?

### ISSUE THREAD

**Issue by rmakarov94** [zelenin/yii2-i18n-module#23]
Hello,
I have issue trying to translate text in controllers.
controllers:
`Yii::$app->language // en (default)`
template: 
`Yii::$app->language // ru (selected)`
Where language is switching? or how to switch it manually?
Thank.

**Comment by zelenin** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-i18n.md
